declare module 'vuedraggable';
declare module 'vue2-scrollspy';
declare module 'get-video-id';
declare module 'vue-pdf';
declare module 'pdfmake/build/pdfmake';
declare module 'pdfmake/build/vfs_fonts';
declare module 'vue-html2canvas';
declare module 'vue-swatches';
declare module 'vue-draggable-resizable';
